[refactor] : Dropdown 컴포넌트 리팩터링
programmers-kdt-full-stack-3rd/community-board pull request #329
Opened 2024-10-31 15:26 UTC by yejunian

## #️⃣ 연관된 이슈

- #225
  - #267

## 📝 작업 내용

- 이전에는 드롭다운 메뉴 컴포넌트 밖으로 ref를 노출하여, `<Header>`에서 useRef 훅으로 생성한 ref를 전달받는 방식이었습니다.
  - ref는 일반적인 prop처럼 보이지만, 외부에서 전달받으려면 일반 prop과 다르게 forwardRef를 활용해야 합니다.
  - forwardRef를 활용하는 패턴이 혼란을 일으켰으므로, ref를 드롭다운 밖으로 노출하지 않도록 구조를 변경했습니다.
  - 변경된 코드에서는 `<Dropdown>` 내부에서만 ref를 사용하며, 토글 버튼도 내부로 옮겼습니다.
  - (현재는 메뉴 박스가 토글 버튼 우측에 정렬되도록 구현했으며, 나중에 다른 곳에서도 사용해야 한다면 그때 정렬 기능을 확장해야 하는 상태입니다.)
- 작업 중 `<Dropdown>` 컴포넌트 외 변경사항 (이런 수정은 자제하겠습니다..)
  - `<Header>` 컴포넌트
    - 인라인 스타일을 Tailwind CSS 클래스로 교체
    - 헤더 우측 분기 처리 정리
  - `<Button>` 컴포넌트
    - outline/text variant 버튼 hover 시 배경색 정리 (opacity 부여)
    - `noInternalStyle` prop을 추가하여, 스타일 없는 버튼 사용 가능하도록 처리
- 실제 렌더되는 비주얼은 작업 전과 비슷하여, 스크린샷은 생략합니다.

### `<Dropdown>` 컴포넌트 사용 예시

<details><summary>Details</summary>

```tsx
const Sample = () => {
  const [isOpen, setIsOpen] = useState(false);

  // 항목 클릭 이벤트 핸들러 작성 (파라미터 불필요)

  return (
    <Dropdown
      isOpen={isOpen}
      onToggle={setIsOpen}
      toggleLabel="메뉴" // ReactNode이므로 JSX 구문도 가능
    >
      <Dropdown.Item
        icon={<Icon1 />}
        onClick={handleItem1Click}
      >
        항목 1
      </Dropdown.Item>

      <Dropdown.Item
        icon={<Icon2 />}
        onClick={handleItem2Click}
      >
        항목 2
      </Dropdown.Item>

      {/* ... */}

      <Dropdown.Item
        icon={<IconN />}
        onClick={handleItemNClick}
      >
        항목 N
      </Dropdown.Item>
    </Dropdown>
  );
};
```

</details> 

## 💬 리뷰 요구사항

- `<Dropdown>` 자체 내용은 `client/src/component/common/Dropdown.tsx`에 있습니다.
- `<Dropdown>` 컴포넌트를 직접 활용하는 부분은 `client/src/component/Header/UserDropdown.tsx`에 있습니다.
- 잘못 구현되었거나 오작동하는 부분 있으면 말씀해 주세요.

2024-11-01 03:44 UTC, HungKungE approved these changes
전반적으로 코드가 깔끔해지고
재사용성이 좋아진 것 같습니다!
나중에 다른 프로젝트 할 때, 가져다가 써도 되겠네요
수고하셨습니다

2024-11-01 03:44 UTC, HungKungE commented on client/src/component/common/Button.tsx
> +			text: "text-blue-800 hover:bg-blue-600/20",
bg-blue-600/20은 뭘 의미하나요?

2024-11-01 05:25 UTC, yejunian commented on client/src/component/common/Button.tsx
> +			text: "text-blue-800 hover:bg-blue-600/20",
뒤에 붙는 `/N`은 해당 속성 opacity N%입니다. 각종 컬러 뒤에 붙일 수 있는데, 엘리먼트 전체에 불투명도를 주는 `opacity-...`와는 다르게 해당 컬러(글자색, 배경색 등)에만 불투명도를 줍니다.

https://tailwindcss.com/docs/background-color#changing-the-opacity

2024-11-01 07:20 UTC, HungKungE commented on client/src/component/common/Button.tsx
> +			text: "text-blue-800 hover:bg-blue-600/20",
오우 완전 꿀팁이네요!
맨날 div 안에 p 태그로 텍스트 감싸서 p에대가 opacity줬는데
편하고 좋네요!

2024-11-03 12:21 UTC, hojun3377 requested changes
아래 문제 이외에는 코드가 깔끔해져서 더 가독성이 좋아진 것 같습니다!

2024-11-03 12:21 UTC, hojun3377 commented on client/src/component/common/Dropdown.tsx
> +					onClick={handleToggle}
문제가 되는 click 이벤트 입니다.

2024-11-03 12:21 UTC, hojun3377 commented on client/src/component/common/Dropdown.tsx
> +				document.removeEventListener("mousedown", handleOutsideClick);
테스트해보니 토글을 클릭하면 dropdown이 생겼다가 없어지고 다시 생기는 문제가 있습니다.

mouse 이벤트의 실행 순서가 mousedown 이벤트 -> click 이벤트 -> mousedown 이벤트 이기 때문인 것 같습니다,

참고: [마우스 이벤트 - 모던 Javascript 튜토리얼](https://ko.javascript.info/mouse-events-basics)

2024-11-04 02:35 UTC, yejunian commented on client/src/component/common/Dropdown.tsx
> +				document.removeEventListener("mousedown", handleOutsideClick);
새로 클론하고 브랜치 다시 받아서 테스트해 봤는데, 말씀해 주신 문제가 재현되지 않습니다. (다크 모드도 동일)

<img src="https://github.com/user-attachments/assets/1fa73693-7b47-4adc-9352-607fe611d136" width="240">

ref가 드롭다운 메뉴와 토글 버튼을 감싸는 `<div>`에 걸려 있기 때문에, 토글을 클릭하더라도 (ref를 걸어 둔 `<div>` 내부에 있으므로) handleOutsideClick 함수 안에서 `onToggle(false)`를 호출하지 않습니다. 아래와 같이 handleOutsideClick 함수에서 로그를 찍도록 수정하고, 드롭다운을 열고 다시 토글을 눌러 보면 `inside`를 출력합니다.

```tsx
const handleOutsideClick = (event: MouseEvent) => {
  if (
    rootRef.current &&
    !rootRef.current.contains(event.target as Node)
  ) {
    console.log("outside");
    onToggle(false);
  } else {
    console.log("inside");
  }
};
```

2024-11-04 03:37 UTC, yejunian commented on client/src/component/Header/UserDropdown.tsx
>  			() => getUserMyself(),
useLayoutEffect는 브라우저 repaint 전에 수행되고, useLayoutEffect와 그 내부에서 동기적으로 발생하는 state 변화는 브라우저의 repaint 동작을 일시적으로 막습니다. 공식 문서에서도 useLayoutEffect는 브라우저 paint 전에 완수되어야 하는 상황에서만 사용하도록(예: 툴팁의 위치 계산) 안내하고 있습니다.

여기서는 API 호출 결과가 화면에 표시되는 콘텐츠를 변화시키기는 하지만, 비동기적으로 처리되므로 useLayoutEffect의 목적을 살릴 수 없어서 useEffect로 바꿨습니다. (비동기 처리이므로 useLayoutEffect를 쓰더라도 상태 변화가 렌더 사이클 후에 이루어집니다.)

- [useLayoutEffect](https://react.dev/reference/react/useLayoutEffect)
- [useEffect → Troubleshooting → My Effect does something visual, and I see a flicker before it runs](https://react.dev/reference/react/useEffect#my-effect-does-something-visual-and-i-see-a-flicker-before-it-runs)

논외로, 이제는 로그인 시 서버에서 유저 이메일 정보를 함께 전달하기 때문에, 이 부분을 제거할 수 있습니다. 이 내용은 따로 PR을 올리겠습니다!

2024-11-04 04:14 UTC, HungKungE commented on client/src/component/common/Dropdown.tsx
> +				document.removeEventListener("mousedown", handleOutsideClick);
해당 브랜치는 문제가 없고,
예전 브랜치에서는 호준님이 말씀하신 문제 확인했습니다.
이 PR 머지되면 해결되는 문제입니다.

2024-11-04 04:20 UTC, HungKungE commented on client/src/component/common/Dropdown.tsx
> +				document.removeEventListener("mousedown", handleOutsideClick);
PR 이전
![Nov-04-2024 13-15-31](https://github.com/user-attachments/assets/ba2c2a23-469d-4bb3-a524-dd4811c62c59)

PR 이후
![Nov-04-2024 13-20-08](https://github.com/user-attachments/assets/96b7d677-1f3b-4b47-be91-abe68215a3cb)

2024-11-04 04:49 UTC, hojun3377 commented on client/src/component/common/Dropdown.tsx
> +				document.removeEventListener("mousedown", handleOutsideClick);
docker image 문제로 코드가 다시 빌드되지 않아서 생겼던 제 문제 같습니다.

image 지우고 다시 실행해보니 아래 흐름처럼 정상적으로 동작합니다!
inside: handleOutsideClick => inside => handleTogle
outside: handleOutsideClick => outside

2024-11-04 04:49 UTC, hojun3377 approved these changes

2024-11-04 11:24 UTC, estiemoon approved these changes
LGTM입니다!

2024-11-04 11:33 UTC, merged