[FE] 로그인 화면 구현
programmers-kdt-full-stack-3rd/community-board pull request #76
Opened 2024-07-14 14:47 UTC by Siltarae

## #️⃣ 연관된 이슈

- #71

## 📝 작업 내용

- [x] 사용자 이메일과 비밀번호 입력 폼 생성
- [x] 로그인 버튼 구현 및 클릭 이벤트 처리
- [x] 로그인 성공시 유저 페이지로 리다이렉트
- [x] 로그인 실패 시 에러 메시지 표시

## 향후 추가 사항
 - [ ] Zustand 세팅 후 로그인 성공 시 Zustand 저장소에 다음 정보 저장:
     - 사용자 닉네임
     - 로그인 시간
     - 로그인 여부(boolean)
 - [ ] 로그인 헤더 추가 후 로그인 버튼 누른 시점의 페이지로 이동

### 🖼️ 스크린샷
![image](https://github.com/user-attachments/assets/80ada513-e787-442e-baa2-8bada333342b)

## 💬 리뷰 요구사항(선택)

잘못 구현된 부분이나 이상한 부분 있으면 말해주세요.

2024-07-14 15:35 UTC, yejunian approved these changes
LGTM입니다.

2024-07-15 03:38 UTC, HungKungE requested changes
LGTM~

2024-07-15 03:38 UTC, HungKungE commented on client/src/page/User/Login.tsx
> +    if (!email) {
## 의견
email, password를 입력하지 않았을 때, 각각 버튼을 클릭하는 상황을 에러 핸들링 하셨군요.
이 방법도 좋은 것 같습니다. 특히, 어떤 부분이 틀렸는지 가시적으로 보여줘서 좋다고 생각합니다.

## nit : 다른 방식도 있습니다. 그렇구나~하고 읽어만 주세요
- login button의 disabled 설정
    - 이메일, 비밀번호 정규 표현식을 모두 지켰으면 false
- 이메일, 비밀번호 규칙을 지키지 않았을 때 사용자에게 보여주기
    - 정규 표현식을 지켰는지, 아닌지에 따라 input의 style 바꾸기 + 문구 보여주기
    - 지켰음 : 테두리 초록색 + 글씨 초록색
    - 안지킴 : 테두리 빨간색 + 글씨 빨간색

2024-07-15 03:38 UTC, HungKungE commented on client/src/page/User/Login.tsx
> +            placeholder="비밀번호를 입력하세요."
nit : 비밀번호 규칙을 쓰는 것도 좋다고 생각해요~

2024-07-15 03:40 UTC, HungKungE commented
어우, 잘못눌러서 approve하려다가 requested change가 되었네요
그냥 무시하시고 merge하시면 될 것 같습니다.

2024-07-15 04:02 UTC, merged

2024-07-23 13:12 UTC, jun108059 reviewed
LGTM입니다